In [1]:
!pip install numpy 


In [2]:
pip install tensorflow

  Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
  Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)
Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.


  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
optree 0.17.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
pandas 3.0.0 requires numpy>=1.26.0; python_version < "3.14", but you have numpy 1.24.3 which is incompatible.
python-docx 1.1.2 requires typing-extensions>=4.9.0, but you have typing-extensions 4.5.0 which is incompatible.
scipy 1.17.0 requires numpy<2.7,>=1.26.4, but you have numpy 1.24.3 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.24.3 which is incompatible.
sqlalchemy 2.0.25 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
streamlit 1.30.0 requires pandas<3,>=1.3.0, but you have pandas 3.0.0 wh

In [4]:
import numpy as np

np.__version__

'1.24.3'

In [5]:
np.array([1,2,3])  ## one dim array

array([1, 2, 3])

In [6]:
np.array([[1,2,3],[4,5,6],[7,8,9]])  ## two dim array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,21,31],[41,51,61],[17,18,19]]])    ### three dim array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 21, 31],
        [41, 51, 61],
        [17, 18, 19]]])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.random.randint(10,size = (3,4))

array([[3, 1, 7, 5],
       [7, 0, 0, 7],
       [5, 5, 6, 9]])

In [14]:
np.random.normal(22,5,(3,4))

array([[24.00311076, 14.08388896, 29.19773506, 26.33051536],
       [19.7283892 , 15.61824092, 16.24757708, 21.22095527],
       [24.76542151, 20.08831842, 16.80065412, 21.72632398]])

In [15]:
np.random.normal(1,5,10)

array([-8.13744594,  3.68905479,  4.75739006, -5.95668721,  6.18437566,
        6.544558  , -4.85098921,  5.32580378, -1.5691138 ,  1.5362821 ])

In [20]:
x1 = np.random.randint(10,size = 6)
x1

array([8, 6, 5, 9, 1, 9])

In [26]:
x1[0]

8

In [28]:
x1[2:5]

array([5, 9, 1])

In [29]:
x1[-1]

9

In [22]:
x2 = np.random.randint(10,size = (3,4))
x2

array([[9, 1, 8, 9],
       [4, 5, 2, 1],
       [4, 1, 6, 7]])

In [32]:
x2[0:2,0:2]

array([[9, 1],
       [4, 5]])

In [33]:
x2[1::,1:3]

array([[5, 2],
       [1, 6]])

In [35]:
subset = x2[1::,2::]
subset

array([[2, 1],
       [6, 7]])

In [36]:
x2[-1,-1]

7

In [37]:
x2[2,3]

7

In [25]:
x3 = np.random.randint(10, size = (3,3,4))  #### number of 2-D matrices , rows, columns 
x3

array([[[9, 7, 6, 0],
        [4, 3, 9, 1],
        [1, 3, 7, 5]],

       [[5, 4, 5, 8],
        [6, 8, 8, 4],
        [9, 4, 9, 2]],

       [[0, 6, 2, 7],
        [8, 6, 8, 5],
        [7, 8, 0, 2]]])

In [38]:
x3[0,0,0]

9

In [39]:
x3[1,1::,2::]

array([[8, 4],
       [9, 2]])

In [40]:
x1.ndim

1

In [41]:
x2.ndim

2

In [43]:
x3.ndim

3

In [45]:
x1.shape

(6,)

In [46]:
x2.shape

(3, 4)

In [47]:
x3.shape

(3, 3, 4)

In [49]:
X2_a = np.random.randint(10,size = (3,4))
X2_a

array([[6, 3, 1, 4],
       [0, 9, 5, 7],
       [7, 9, 1, 2]])

In [57]:
Mymat = x2-X2_a
Mymat

array([[ 3, -2,  7,  5],
       [ 4, -4, -3, -6],
       [-3, -8,  5,  5]])

In [52]:
Mymat.min()

4

In [53]:
Mymat.max()

15

In [54]:
Mymat.mean()

9.25

In [55]:
Mymat.std()

3.418698582794336

In [56]:
Mymat.sum()

111